{
 "title": "WAN Ops 2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1>CiscoLive Internet / WAN Stats</h1></center>"
   }
  },
  { "title": "Traffic Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\" or r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"HundredGigE2/1/0\" or r[\"interface\"] == \"HundredGigE0/1/0\" or r[\"interface\"] == \"TenGigabitEthernet1/1/8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv4-in-octets\" or r[\"_field\"] == \"ipv6-in-octets\")\r\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "Total Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\" or r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"HundredGigE2/1/0\" or r[\"interface\"] == \"HundredGigE0/1/0\" or r[\"interface\"] == \"TenGigabitEthernet1/1/8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv4-out-octets\" or r[\"_field\"] == \"ipv6-out-octets\")\r\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "Internet  Upload",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\" or r[\"device\"] == \"CLNOC-ASR1009-2\")\n  |> filter(fn: (r) => r[\"interface\"] == \"HundredGigE0/1/0\" or r[\"interface\"] == \"TenGigabitEthernet1/1/8\"  or r[\"interface\"] == \"HundredGigE2/1/0\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv4-out-octets\" or r[\"_field\"] == \"ipv6-out-octets\")\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: 2m, fn: mean)\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "IPv4 Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\" or r[\"device\"] == \"CLNOC-ASR1009-2\")\n  |> filter(fn: (r) => r[\"interface\"] == \"HundredGigE0/1/0\" or r[\"interface\"] == \"HundredGigE2/1/0\" or r[\"interface\"] == \"TenGigabitEthernet1/1/8\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv4-in-octets\" or r[\"_field\"] == \"ipv4-out-octets\")\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: 2m, fn: mean)\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "IPv4 In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\" or r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"HundredGigE2/1/0\" or r[\"interface\"] == \"HundredGigE0/1/0\" or r[\"interface\"] == \"TenGigabitEthernet1/1/8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv4-in-octets\")\r\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "IPv4 Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\" or r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"HundredGigE2/1/0\" or r[\"interface\"] == \"HundredGigE0/1/0\" or r[\"interface\"] == \"TenGigabitEthernet1/1/8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv4-out-octets\")\r\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "Internet Download",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\" or r[\"device\"] == \"CLNOC-ASR1009-2\")\n  |> filter(fn: (r) => r[\"interface\"] == \"HundredGigE0/1/0\" or r[\"interface\"] == \"HundredGigE2/1/0\" or r[\"interface\"] == \"TenGigabitEthernet1/1/8\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv4-in-octets\" or r[\"_field\"] == \"ipv6-in-octets\")\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: 2m, fn: mean)\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "IPv6 Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\" or r[\"device\"] == \"CLNOC-ASR1009-2\")\n  |> filter(fn: (r) => r[\"interface\"] == \"HundredGigE0/1/0\" or r[\"interface\"] == \"HundredGigE2/1/0\" or r[\"interface\"] == \"TenGigabitEthernet1/1/8\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv6-in-octets\" or r[\"_field\"] == \"ipv6-out-octets\")\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: 2m, fn: mean)\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "IPv6 In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\" or r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"HundredGigE2/1/0\" or r[\"interface\"] == \"HundredGigE0/1/0\" or r[\"interface\"] == \"TenGigabitEthernet1/1/8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv6-in-octets\")\r\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "IPv6 Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\" or r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"HundredGigE2/1/0\" or r[\"interface\"] == \"HundredGigE0/1/0\" or r[\"interface\"] == \"TenGigabitEthernet1/1/8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv6-out-octets\")\r\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  { "title": "BGP Routes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "IPv4 BGP Routes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"65.56.159.229\" or r[\"neighbor-id\"] == \"66.77.8.142\" or r[\"neighbor-id\"] == \"63.146.126.142\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "IPv6 BGP Routes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"2001:1900:2100:31::16B1\" or r[\"neighbor-id\"] == \"2001:428:C801:0:63:146:126:142\" or r[\"neighbor-id\"] == \"2001:428:CE00:2:66:77:8:1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Lumen v4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"65.56.159.229\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Lumen v6",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"2001:1900:2100:31::16B1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ASR-1 v4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"63.231.216.8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ASR-1 v6",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"2001:428:CE01:1111:63:231:216:8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "SUN v4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"63.146.126.142\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "SUN v6",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"2001:428:CE00:2:66:77:8:1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "SUN v4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"63.146.126.142\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "SUN v6",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"2001:428:CE00:2:66:77:8:1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "DEN v4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"66.77.8.142\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "DEN v6",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"2001:428:C801:0:63:146:126:142\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "DEN v4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"66.77.8.142\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "DEN v6",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"2001:428:C801:0:63:146:126:142\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "ASR1K-1 Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
   "repeat": "WAN_Router",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"free_memory\" or r[\"_field\"] == \"used_memory\" or r[\"_field\"] == \"total_memory\")\n  |> filter(fn: (r) => r[\"name\"] == \"Processor\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic\")\n  |> filter(fn: (r) => r[\"source\"] == \"CLNOC-ASR1009-1\")\n  |> filter(fn: (r) => r[\"subscription\"] == \"102\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU 1 Min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 21 },
   "repeat": "WAN_Router",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"_field\"] == \"one_minute\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"source\"] == \"CLNOC-ASR1009-1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "CPU 5 Min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 21 },
   "repeat": "WAN_Router",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"_field\"] == \"five_minutes\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"source\"] == \"CLNOC-ASR1009-1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "QFP Utilization - 1 Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wan-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"OneMin\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ASR-1 Hu2/1/0 In",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"HundredGigE2/1/0\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv4-in-octets\" or r[\"_field\"] == \"ipv6-in-octets\")\r\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "ASR-1 Hu2/1/0 Out",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"HundredGigE2/1/0\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv4-out-octets\" or r[\"_field\"] == \"ipv6-out-octets\")\r\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "ASR-1 Hu0/1/0 In",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"HundredGigE0/1/0\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv4-in-octets\" or r[\"_field\"] == \"ipv6-in-octets\")\r\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "ASR-1 Hu0/1/0 Out",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"HundredGigE0/1/0\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv4-out-octets\" or r[\"_field\"] == \"ipv6-out-octets\")\r\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "QFP Utilization - 5 Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wan-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"FiveMin\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "CPU 5 Sec",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 25 },
   "repeat": "WAN_Router",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"_field\"] == \"five_seconds\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"source\"] == \"CLNOC-ASR1009-1\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ASR-1 Te1/1/8 In",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"TenGigabitEthernet1/1/8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv4-in-octets\" or r[\"_field\"] == \"ipv6-in-octets\")\r\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "ASR-1 Te1/1/8 Out",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"TenGigabitEthernet1/1/8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv4-out-octets\" or r[\"_field\"] == \"ipv6-out-octets\")\r\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  { "title": "ASR1K-2 Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"free_memory\" or r[\"_field\"] == \"used_memory\" or r[\"_field\"] == \"total_memory\")\n  |> filter(fn: (r) => r[\"name\"] == \"Processor\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic\")\n  |> filter(fn: (r) => r[\"source\"] == \"CLNOC-ASR1009-2\")\n  |> filter(fn: (r) => r[\"subscription\"] == \"102\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU 1 Min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"_field\"] == \"one_minute\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"source\"] == \"CLNOC-ASR1009-2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "CPU 5 Min",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"_field\"] == \"five_minutes\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"source\"] == \"CLNOC-ASR1009-2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "QFP Utilization - 1 Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wan-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"OneMin\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ASR-2 Hu0/1/0 In",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"HundredGigE0/1/0\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv4-in-octets\" or r[\"_field\"] == \"ipv6-in-octets\")\r\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "ASR-2 Hu0/1/0 Out",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"HundredGigE0/1/0\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv4-out-octets\" or r[\"_field\"] == \"ipv6-out-octets\")\r\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "ASR-2 Te1/1/8 In",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"TenGigabitEthernet1/1/8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv4-in-octets\" or r[\"_field\"] == \"ipv6-in-octets\")\r\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "ASR-2 Te1/1/8 out",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: -2h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interface-ipv4v6\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"TenGigabitEthernet1/1/8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ipv4-out-octets\" or r[\"_field\"] == \"ipv6-out-octets\")\r\n  |> map(fn: (r) => ({r with _value: int(v: r._value) * 8}))\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "QFP Utilization - 1 Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wan-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"FiveMin\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "CPU 5 Sec",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"_field\"] == \"five_seconds\")\n  |> filter(fn: (r) => r[\"path\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"source\"] == \"CLNOC-ASR1009-2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "ASR-2 v4",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"63.231.216.9\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "ASR-2 v6",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"2001:428:CE01:1111:63:231:216:9\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  }
 ]
}