{
 "title": "WAN BGP Routes",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center><h1> CiscoLive WAN BGP Routes </h1></center>"
   }
  },
  { "title": "IPv4 BGP Routes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "IPv4 BGP Routes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"65.56.159.229\" or r[\"neighbor-id\"] == \"66.77.8.142\" or r[\"neighbor-id\"] == \"63.146.126.142\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ASR-1 - Lumen v4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"65.56.159.229\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ASR-2 - ASR-1 v4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"63.231.216.8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ASR-1 - Sunnyvale v4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"63.146.126.142\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ASR-2 - Sunnyvale v4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"63.146.126.142\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ASR-1 - Denver v4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"66.77.8.142\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ASR-2 - Denver v4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"66.77.8.142\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "IPv6 BGP Routes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "IPv6 BGP Routes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"2001:1900:2100:31::16B1\" or r[\"neighbor-id\"] == \"2001:428:C801:0:63:146:126:142\" or r[\"neighbor-id\"] == \"2001:428:CE00:2:66:77:8:1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ASR-1 - Lumen v6",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"2001:1900:2100:31::16B1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ASR-2 - ASR-1 v6",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"2001:428:CE01:1111:63:231:216:8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ASR-1 - Sunnyvale v6",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"2001:428:CE00:2:66:77:8:1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ASR-2 - Sunnyvale v6",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"2001:428:CE00:2:66:77:8:1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ASR-1 - Denver v6",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-1\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"2001:428:C801:0:63:146:126:142\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "ASR-2 - Denver v6",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-bgp-oper:custom\")\r\n  |> filter(fn: (r) => r[\"device\"] == \"CLNOC-ASR1009-2\")\r\n  |> filter(fn: (r) => r[\"neighbor-id\"] == \"2001:428:C801:0:63:146:126:142\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"current-prefixes\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}