{
 "title": "Wireless Client Counts",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wirelessclientcounts\")\n  |> filter(fn: (r) => r[\"controller\"] == \"CLUS-KNWLC-SSO-1\" or r[\"controller\"] == \"CLUS-WLC-SSO-1\" or r[\"controller\"] == \"Meraki\" or r[\"controller\"] == \"WLC-AIRRM-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"80211ac-count\" or r[\"_field\"] == \"80211ax2-count\" or r[\"_field\"] == \"80211ax5-count\" or r[\"_field\"] == \"80211n24-count\" or r[\"_field\"] == \"80211n5-count\" or r[\"_field\"] == \"total-count\")\n  |> last()\n  |> group()\n  |> sum()\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<p style=\"font-size: 3.2em; padding: 70px 0;\">Total Wireless Clients</p>"
   }
  },
  {
   "title": "Main Conference WLC SSO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wirelessclientcounts\")\n  |> filter(fn: (r) => r[\"controller\"] == \"CLUS-WLC-SSO-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"80211ac-count\" or r[\"_field\"] == \"80211ax2-count\" or r[\"_field\"] == \"80211ax5-count\" or r[\"_field\"] == \"80211n24-count\" or r[\"_field\"] == \"80211n5-count\")\n  |> last()\n  |> group()\n  |> sum()\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Key Note WLC SSO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wirelessclientcounts\")\n  |> filter(fn: (r) => r[\"controller\"] == \"CLUS-KNWLC-SSO-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"80211ac-count\" or r[\"_field\"] == \"80211ax2-count\" or r[\"_field\"] == \"80211ax5-count\" or r[\"_field\"] == \"80211n24-count\" or r[\"_field\"] == \"80211n5-count\")\n  |> last()\n  |> group()\n  |> sum()\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "AIRRM WLC SSO",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wirelessclientcounts\")\n  |> filter(fn: (r) => r[\"controller\"] == \"WLC-AIRRM-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"80211ac-count\" or r[\"_field\"] == \"80211ax2-count\" or r[\"_field\"] == \"80211ax5-count\" or r[\"_field\"] == \"80211n24-count\" or r[\"_field\"] == \"80211n5-count\")\n  |> last()\n  |> group()\n  |> sum()\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Meraki",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wirelessclientcounts\")\n  |> filter(fn: (r) => r[\"controller\"] == \"Meraki\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total-count\")\n  |> last()\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wirelessclientcounts\")\n  |> filter(fn: (r) => r[\"controller\"] == \"CLUS-WLC-SSO-1\" or r[\"controller\"] == \"CLUS-KNWLC-SSO-1\" or r[\"controller\"] == \"WLC-AIRRM-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"80211a-count\" or r[\"_field\"] == \"80211ac-count\" or r[\"_field\"] == \"80211ax2-count\" or r[\"_field\"] == \"80211ax5-count\" or r[\"_field\"] == \"80211b-count\" or r[\"_field\"] == \"80211g-count\" or r[\"_field\"] == \"80211n24-count\" or r[\"_field\"] == \"80211n5-count\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wirelessclientcounts\")\n  |> filter(fn: (r) => r[\"controller\"] == \"Meraki\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total-count\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}