{
 "title": "Wireless LAN Controller Redundancy",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "WLC",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(bucket: \"CLNOC\", measurement: \"wireless-stats\", tag: \"wlc\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Combined SSO System Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wireless-stats\")\n  |> filter(fn: (r) => r[\"metric\"] == \"redundancy\")\n  |> filter(fn: (r) => r[\"wlc\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sysuptime\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Switchovers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wireless-stats\")\n  |> filter(fn: (r) => r[\"metric\"] == \"redundancy\")\n  |> filter(fn: (r) => r[\"wlc\"] == \"CLUS-WLC-SSO-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"switchovers\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Standby Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wireless-stats\")\n  |> filter(fn: (r) => r[\"metric\"] == \"redundancy\")\n  |> filter(fn: (r) => r[\"wlc\"] == \"CLUS-WLC-SSO-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"standbyfailures\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Last Switchover Reason",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wireless-stats\")\n  |> filter(fn: (r) => r[\"metric\"] == \"redundancy\")\n  |> filter(fn: (r) => r[\"wlc\"] == \"CLUS-WLC-SSO-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"lastswitchoverreason\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Hardware Mode",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wireless-stats\")\n  |> filter(fn: (r) => r[\"metric\"] == \"redundancy\")\n  |> filter(fn: (r) => r[\"wlc\"] == \"CLUS-WLC-SSO-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"hardwaremode\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Configured Redundancy Mode",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wireless-stats\")\n  |> filter(fn: (r) => r[\"metric\"] == \"redundancy\")\n  |> filter(fn: (r) => r[\"wlc\"] == \"CLUS-WLC-SSO-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"configuredredundancymode\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Operating Redundancy Mode",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wireless-stats\")\n  |> filter(fn: (r) => r[\"metric\"] == \"redundancy\")\n  |> filter(fn: (r) => r[\"wlc\"] == \"CLUS-WLC-SSO-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"operatingredundancymode\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Communications State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wireless-stats\")\n  |> filter(fn: (r) => r[\"metric\"] == \"redundancy\")\n  |> filter(fn: (r) => r[\"wlc\"] == \"CLUS-WLC-SSO-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"communications\")\n  |> last()\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "options": {
    "content": "<center><img src=\"https://www.cisco.com/c/dam/en/us/products/collateral/wireless/catalyst-9800-series-wireless-controllers/nb-06-cat9800-80-wirel-mod-data-sheet-ctp-en.docx/_jcr_content/renditions/nb-06-cat9800-80-wirel-mod-data-sheet-ctp-en_0.png\n\" alt=\"Catalust 9800-80 WLC\">\n<h2>Primary</h2></center>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "options": {
    "content": "<center><img src=\"https://www.cisco.com/c/dam/en/us/products/collateral/wireless/catalyst-9800-series-wireless-controllers/nb-06-cat9800-80-wirel-mod-data-sheet-ctp-en.docx/_jcr_content/renditions/nb-06-cat9800-80-wirel-mod-data-sheet-ctp-en_0.png\n\" alt=\"Catalust 9800-80 WLC\">\n<h2>Secondary</h2></center>"
   }
  },
  {
   "title": "Software State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wireless-stats\")\n  |> filter(fn: (r) => r[\"metric\"] == \"redundancy\")\n  |> filter(fn: (r) => r[\"wlc\"] == \"CLUS-WLC-SSO-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"priswstate\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Primary Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wireless-stats\")\n  |> filter(fn: (r) => r[\"metric\"] == \"redundancy\")\n  |> filter(fn: (r) => r[\"wlc\"] == \"CLUS-WLC-SSO-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"priuptimeincurrentstate\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Software State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wireless-stats\")\n  |> filter(fn: (r) => r[\"metric\"] == \"redundancy\")\n  |> filter(fn: (r) => r[\"wlc\"] == \"CLUS-WLC-SSO-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"secswstate\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Secondary Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wireless-stats\")\n  |> filter(fn: (r) => r[\"metric\"] == \"redundancy\")\n  |> filter(fn: (r) => r[\"wlc\"] == \"CLUS-WLC-SSO-1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"secuptimeincurrentstate\")\n  |> last()\n"
    }
   ]
  }
 ]
}