{
 "title": "WNCd",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "WLC",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(bucket: \"CLNOC\", measurement: \"wireless-stats\", tag: \"device\")"
   },
   {
    "name": "WNCd_instance",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(bucket: \"CLNOC\", measurement: \"wireless-stats\", tag: \"instance\")"
   }
  ]
 },
 "panels": [
  {
   "title": "WNCd Process CPU for $WLC",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wireless-stats\")\n  |> filter(fn: (r) => r[\"metric\"] == \"wncd\")\n  |> filter(fn: (r) => r[\"device\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"onemincpu\")\n  |> filter(fn: (r) => r[\"instance\"] == \"wncd_0\" or r[\"instance\"] == \"wncd_1\" or r[\"instance\"] == \"wncd_2\" or r[\"instance\"] == \"wncd_3\" or r[\"instance\"] == \"wncd_4\" or r[\"instance\"] == \"wncd_5\" or r[\"instance\"] == \"wncd_6\" or r[\"instance\"] == \"wncd_7\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "$WNCd_instance",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2.4, "x": 0, "y": 9 },
   "repeat": "WNCd_instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wireless-stats\")\n  |> filter(fn: (r) => r[\"metric\"] == \"wncd\")\n  |> filter(fn: (r) => r[\"device\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"instance\"] == \"${WNCd_instance}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"onemincpu\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Site",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2.4, "x": 0, "y": 15 },
   "repeat": "WNCd_instance",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: -10m, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wireless-stats\")\n  |> filter(fn: (r) => r[\"metric\"] == \"wncd\")\n  |> filter(fn: (r) => r[\"device\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"instance\"] == \"${WNCd_instance}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sitetag\")\n  |> drop(columns: [\"_time\"])\n  |> last()\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "APs Joined",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2.4, "x": 0, "y": 17 },
   "repeat": "WNCd_instance",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"CLNOC\")\n  |> range(start: -60m, stop: now())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"wireless-stats\")\n  |> filter(fn: (r) => r[\"metric\"] == \"wncd\")\n  |> filter(fn: (r) => r[\"device\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"instance\"] == \"${WNCd_instance}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"apsjoined\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}